#!/bin/bash
set -e

WRAPPER_SCRIPT=/usr/bin/rkllm-server-flask

# Check if flask is installed
if ! python3 -c "import flask" 2>/dev/null; then
    echo "-------- Required dependency flask is not installed. Installing it now... --------"
    pip3 install flask==2.2.2 Werkzeug==2.2.2 --break-system-packages
fi

echo "-------- Installing wrapper for rkllm_server_flask --------"
echo "#!/bin/bash" > "$WRAPPER_SCRIPT"
echo "python3 /usr/bin/rkllm_server_flask.py" >> "$WRAPPER_SCRIPT"
chmod a+x "$WRAPPER_SCRIPT"

exit 0
